// codebase-memory-mcp:start
// Generated by codebase-memory-mcp for OpenCode v2.
import { spawn } from 'node:child_process';
import { Plugin } from '@opencode/plugin';

const BIN = process.env.CBM_BIN ?? 'C:/Users/andre/.local/bin/codebase-memory-mcp.exe';

function augment(tool: string, args: any): Promise<string> {
  return new Promise((resolve) => {
    const child = spawn(BIN, ['hook-augment'], {
      stdio: ['pipe', 'pipe', 'ignore'],
      env: { ...process.env, CBM_LOG_LEVEL: 'error' },
    });
    let out = '';
    child.stdout.on('data', (d) => (out += d.toString()));
    child.on('error', () => resolve(''));
    child.on('close', () => resolve(out));
    child.stdin.end(JSON.stringify({
      hook_event_name: 'PreToolUse',
      tool_name: tool,
      tool_input: args ?? {},
    }));
  });
}

export default Plugin.define({
  id: 'codebase-memory-augment',
  async setup(ctx) {
    await ctx.tool.hook('execute.after', async (event: any) => {
      const tool = event?.tool === 'grep' ? 'Grep' : event?.tool === 'glob' ? 'Glob' : null;
      if (!tool) return;
      const extra = await augment(tool, event?.input ?? event?.args);
      if (extra && typeof event?.output === 'string') {
        event.output += '\n' + extra;
      } else if (extra && event?.output && typeof event?.output === 'object' && 'content' in event.output) {
        event.output.content += '\n' + extra;
      }
    });
  },
});
// codebase-memory-mcp:end
